### ISSUE TITLE
8266 pinouts

### ISSUE THREAD

**Issue by BuenGenio** [rudydelorenzo/ELMo#1]
Hey, 

I've had a Lolin NodeMCU v3 lying around collecting dust, thought it might be good enough for an OBDII dongle and found your repo. 

I don't see anything that would indicate how to go about connecting the pins on the ESP8266 to the actual car.

Very keen on trying it out. 

Cheers!

**Comment by rudydelorenzo** [comment]
Hey,

This project doesn't interface with the car directly, rather it communicates an ELM wifi reader (like [this one](https://www.amazon.ca/Giveet-Wireless-Scanner-Diagnostic-Smartphone/dp/B076Z91CW3) or [this one](https://www.aliexpress.com/item/1005005604487850.html)). This project connects to those readers and interfaces with the car through them.

Cheers!

**Comment by BuenGenio** [comment]
Roger. Thanks, will come back to it after I get the dongle then :).

Ta
